### PR TITLE
Use more descriptive help for output arg

### PR DESCRIPTION
**Pull request by jordanbtucker**
When I was reading the help, I wasn't sure if `output` expected a filename or a directory.

"Filename of the BNP to create" is more descriptive than "Where to output the BNP" as it indicates a path to a file rather than a path to a directory or file.

### CODE REVIEW

**Review by linktlh — CHANGES_REQUESTED** [review]
I think the issue here is it’s not just the file name, but the path of where to store the newly created bnp.

**Comment by jordanbtucker** [comment]
Yeah, I see your point. I usually take `filename` to mean the path to a file relative to the current working directory, but it can also be taken to mean the last segment in a path (just the name of the file). I think most users comfortable with the command line would understand it means the path of the file, but I can't be sure. I think it's at least more clear that a file is requested rather than a directory.

Maybe, "The path of the BNP file to create"?

**Comment by linktlh** [comment]
How about `The path to store the newly created BNP file` ?

**Comment by jordanbtucker** [comment]
Yes, that is clearer at the expense of maybe being a little verbose.

In 13590a53be1be7501530c1dc7a9f3da5c5faa2a4 you used "The path to the BNP file" which is concise. So, options for `output` could also include:

- The path to the BNP file
- The path to the new BNP file
- The path to the newly created BNP file
- The path to the BNP file to create.

Any of these work as they indicate a file path rather than a directory.

**Comment by linktlh** [comment]
I’d be fine with the last one ;
The path to the BNP file to create

**Pull request merged**
